server:
  port: 8082

spring:
  profiles: default

  dataSource:
    url: jdbc:mysql://db:3306/api
    username: sa
    password: 123456
    initialization-mode: always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


